### ISSUE TITLE
Weird con_notifyX default

### ISSUE THREAD

**Issue by Jelvan1** [JBustos22/oDFe#11]
The current default 48 bothers me. Is it okay to change it to 0?

**Comment by ghost** [comment]
I also thought its a bit weird. Was it set to this position because the lagometer?

**Comment by Jelvan1** [comment]
Yeah, looks like it, but I've always played with the notifications drawn over the lagometer. Let's see what the others say.

**Comment by KG7x** [comment]
Well that's why I did on off
Btw we can change to con_notify_X con_notify_Y for looks like lagometer cvars

**Comment by runaos** [comment]
Original q3 draws over the lagometer too, I think changing it to 0 is okay.
