### ISSUE TITLE
cg_drawgun configurable value of bobbing effect

### ISSUE THREAD

**Issue by neyoneit** [JBustos22/oDFe#17]
Hi good people,

it would be nice to have configurable bobbing effect for weapon model.
Current way is on/off
cg_drawgun 1 - bobbing effect
cg_drawgun 2 - stationary model.
Player model has configurable values and i think it would be nice to have that even for weapon model.

Also moviemakers would love this feature :)

**Comment by Jelvan1** [comment]
This logic resides in the defrag mod. Although it's possible to patch certain defrag versions from the client, I'd rather not do it for features like this.

I propose to close this.

**Comment by Tibuq** [comment]
if on/off is already implemented, why not just keep those and add a third option for stationary model?

**Comment by Jelvan1** [comment]
That option is already present, namely `cg_drawGun 2`.

**Comment by neyoneit** [comment]
request was redirected to cgg.. fyi
