### ISSUE TITLE
Support loading files from separate dir

### ISSUE THREAD

**Issue by Jelvan1** [JBustos22/oDFe#18]
[KittenIgnition] back in the day pan added a cool feature to his engine, `fs_include`, which is basically the same as `fs_extraGames` in mme where you can load files from a separate dir. it's handy for dumbasses like me who map out of our playing folder

**Comment by ghost** [comment]
that might really bein helpful. mapping from the ws-repacks isnt recommended (repacked shaders)

**Comment by KG7x** [comment]
https://github.com/ykram/dfengine/pull/5/commits/d976c14d5d962c05eaf42491cc4a4745fb7757b6
can be improve add option for dl maps this folder
and load this folder after baseq3 and mode
