### ISSUE TITLE
Sound difference

### ISSUE THREAD

**Issue by brandon-df** [JBustos22/oDFe#39]
Sounds in ODFE have slightly higher pitch and come from a different location (in headphones) compared to IDFE. Quality-wise they also sound worse. 

Example: 
IDEF: https://streamable.com/eq7g4h
ODFE: https://streamable.com/vgtn4f

difficult to hear in the clips, but it more pronounced in-game, especially with player jumping sounds

**Comment by Jelvan1** [comment]
Depends which sound driver you use. Using `s_driver wasapi` should give you an identical experience as with iDFe. Since #43 this is again the default.
