### ISSUE TITLE
Add autocompletion for playermodel names including their available skins

### ISSUE THREAD

**Issue by ghost** [JBustos22/oDFe#45]
Since the UI is limited like for the map repaks we cannot select all existing playermodels when using the playermodel repacks.
Adding autocompletion in the console for the modelname and skins would be very handy

**Comment by ghost** [comment]
I've added a semi-working solution in separate autocompletion branch. 
Todo would be get rid of the 'head_' 'upper_' and 'lower_' in the list and not double count them then as well.
could need some help there

**Comment by Jelvan1** [comment]
Please check proposal #47

**Comment by Jelvan1** [comment]
Part of the latest build
