### ISSUE TITLE
#1 FIRST, process name

### ISSUE THREAD

**Issue by neyoneit** [JBustos22/oDFe#5]
please guys make name of .exe to appear as name of process as a title, OBS uses that to pinpoint window and if one pc has more than 1 client open, its confused.. 
id greatly appreciate that

**Comment by Jelvan1** [comment]
Instead of following the filename of the executable, would it be okay to change the window title with an command line argument? One can already change the title of the viewlog/console with `con_title <new_console_title>`. So, I propose to similarly support `cl_title <new_client_title>`.

**Comment by Jelvan1** [comment]
The proposed solution has been implemented.
